// Generated by CoffeeScript 2.7.0
(function() {
  // BoxesPlus - Convert Markdown to PPTX with styled boxes
  // Using CoffeeScript + pptxgenjs
  var PptxGenJS, convertToPptx, createBoxSlide, createTitleSlide, extractBoxes, extractTitle, fs;

  PptxGenJS = require("pptxgenjs");

  fs = require("fs");

  // Parse markdown and extract ASCII boxes
  extractBoxes = function(markdown) {
    var block, boxChars, boxes, c, hasBox, i, len, match, pattern;
    boxes = [];
    pattern = /```\s*\n([\s\S]*?)\n```/g;
    while (match = pattern.exec(markdown)) {
      block = match[1];
      boxChars = {'┌': '┌', '┐': '┐', '└': '└', '┘': '┘', '│': '│', '─': '─', '├': '├', '┤': '┤', '┬': '┬', '┴': '┴', '┼': '┼'};
      hasBox = false;
      for (i = 0, len = block.length; i < len; i++) {
        c = block[i];
        if (c in boxChars) {
          hasBox = true;
          break;
        }
      }
      if (hasBox) {
        boxes.push(block);
      }
    }
    return boxes;
  };

  // Extract title from box content
  extractTitle = function(boxContent) {
    var clean, i, len, line, lines;
    lines = boxContent.split('\n');
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      clean = line.replace(/[│├┤]/g, '').trim();
      if (clean && clean.length < 40) {
        return clean;
      }
    }
    return "内容";
  };

  // Create a slide with title
  createTitleSlide = function(pres, title) {
    var slide;
    slide = pres.addSlide();
    slide.addText(title, {
      x: 0.5,
      y: 2,
      w: 9,
      h: 1,
      fontSize: 36,
      color: "1a365d",
      align: "center"
    });
    return slide;
  };

  // Create styled box on slide
  createBoxSlide = function(pres, boxContent, index) {
    var clean, i, len, line, lines, slide, title, yPos;
    slide = pres.addSlide();
    title = extractTitle(boxContent);
    
    // Header bar
    slide.addShape(pres.ShapeType.rect, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 0.8,
      fill: {
        color: "2c5282"
      }
    });
    slide.addText(title, {
      x: 0.7,
      y: 0.65,
      w: 8.6,
      h: 0.5,
      fontSize: 20,
      color: "ffffff",
      bold: true
    });
    
    // Content box
    slide.addShape(pres.ShapeType.rect, {
      x: 0.5,
      y: 1.5,
      w: 9,
      h: 4,
      fill: {
        color: "f7fafc"
      },
      line: {
        color: "2c5282",
        width: 2
      }
    });
    
    // Extract and display content
    lines = boxContent.split('\n');
    yPos = 1.8;
    for (i = 0, len = lines.length; i < len; i++) {
      line = lines[i];
      clean = line.replace(/[│├┤]/g, '').trim();
      if (clean) {
        slide.addText(clean, {
          x: 0.8,
          y: yPos,
          w: 8.4,
          h: 0.4,
          fontSize: 14,
          color: "2d3748"
        });
        yPos += 0.5;
        if (yPos > 5) {
          break;
        }
      }
    }
    return slide;
  };

  // Main conversion function
  convertToPptx = function(inputFile, outputFile) {
    var box, boxes, content, i, len, pres, title, titleMatch;
    // Read markdown file
    content = fs.readFileSync(inputFile, "utf-8");
    
    // Extract title
    titleMatch = content.match(/^# (.+)$/m);
    title = titleMatch ? titleMatch[1] : "Document";
    
    // Create presentation
    pres = new PptxGenJS();
    
    // Add title slide
    createTitleSlide(pres, title);
    
    // Extract and add boxes
    boxes = extractBoxes(content);
    console.log(`Found ${boxes.length} boxes`);
    for (i = 0, len = boxes.length; i < len; i++) {
      box = boxes[i];
      createBoxSlide(pres, box);
    }
    
    // Save
    return pres.writeFile({
      fileName: outputFile
    }).then(function() {
      return console.log(`Created: ${outputFile}`);
    }).catch(function(err) {
      return console.error(err);
    });
  };

  // Export for use
  module.exports = {extractBoxes, extractTitle, createTitleSlide, createBoxSlide, convertToPptx};

  // Test if run directly
  if (require.main === module) {
    console.log("BoxesPlus CoffeeScript ready!");
    convertToPptx('sources/C01医疗质量与安全管理课程详细教案.md', 'outputs/pptxgenjs/C01_coffee.pptx');
  }

}).call(this);
