// Generated by CoffeeScript 2.7.0
(function() {
  // # C01 医疗质量与安全管理课程详细教案
  // # 这是一个 LitCoffee 文件 - 文档和代码共存

  // 先加载依赖
  var PptxGenJS, THEME, cardSlide, chartSlide, listSlide, pres, quoteSlide, tableSlide, titleSlide;

  PptxGenJS = require("pptxgenjs");

  ({titleSlide, listSlide, cardSlide, tableSlide, quoteSlide, chartSlide, THEME} = require("../api/boxesplus-artist.coffee"));

  // 创建演示文稿
  pres = new PptxGenJS();

  // ---

  // ## 课程信息

  // - **课程名称**：医院医疗质量与安全管理
  // - **课程定位**：医院管理核心模块课程
  // - **课程时长**：12小时（2天）
  // - **课程对象**：医院院长、分管副院长、质控部主任等

  // 封面
  titleSlide(pres, {
    title: "医院医疗质量与安全管理",
    subtitle: "课程详细教案",
    gradient: "blue"
  });

  // 课程信息
  listSlide(pres, {
    title: "课程信息",
    items: ["课程名称：医院医疗质量与安全管理", "课程定位：医院管理核心模块课程", "课程时长：12小时（2天）"]
  });

  // ---

  // ## 课程目标

  // ### 知识目标
  // 1. 掌握医疗质量管理体系的构成
  // 2. 熟悉质量管理工具与方法
  // 3. 了解患者安全目标与措施

  // ### 能力目标
  // 1. 能够建立质量管理体系
  // 2. 能够运用质量管理工具
  // 3. 能够处理质量安全事件

  // ---

  // ## 1.1 医疗质量概念（25分钟）

  // ### 核心内容

  // **一、医疗质量内涵**

  // 使用 API 替代 ASCII boxes
  quoteSlide(pres, {
    quote: "医疗质量是指医疗服务在满足患者及其家属健康需求方面所达到的程度，包括医疗技术质量和服务质量。",
    author: "定义"
  });

  cardSlide(pres, {
    title: "医疗质量内涵",
    columns: 2,
    cards: [
      {
        title: "狭义",
        content: "诊疗质量",
        color: THEME.accent
      },
      {
        title: "广义",
        content: "技术+服务+管理+环境",
        color: THEME.success
      }
    ]
  });

  // **二、医疗质量维度**
  tableSlide(pres, {
    title: "医疗质量维度",
    headers: ["维度", "内容"],
    rows: [["结构质量", "人员、设备、制度、环境"], ["过程质量", "诊疗流程、操作规范"], ["结果质量", "诊疗效果、患者结局"]]
  });

  // ---

  // ## 1.2 医疗质量管理体系（20分钟）

  // ### 核心内容

  // **一、体系架构**
  cardSlide(pres, {
    title: "质量管理体系要素",
    columns: 2,
    cards: [
      {
        title: "组织架构",
        content: "质量管理委员会\n科室质控小组",
        color: THEME.accent
      },
      {
        title: "制度体系",
        content: "质量管理制度\n操作规范流程",
        color: THEME.success
      },
      {
        title: "监测评价",
        content: "指标监测\n定期评价",
        color: THEME.warning
      },
      {
        title: "持续改进",
        content: "PDCA循环\n质量改进项目",
        color: THEME.danger
      }
    ]
  });

  // ---

  // ## 保存文件
  pres.writeFile({
    fileName: "../outputs/C01测试.pptx"
  }).then(function() {
    return console.log("✅ Created: C01测试.pptx");
  }).catch(function(err) {
    return console.error(err);
  });

}).call(this);
