// Generated by CoffeeScript 2.7.0
(function() {
  // BoxesPlus Artist v2 - 完整演示 (简化版)
  // 用法: coffee demo-artist.coffee
  var PptxGenJS, THEME, cardSlide, comparisonSlide, endSlide, flowSlide, listSlide, pres, quoteSlide, tableSlide, timelineSlide, titleSlide;

  PptxGenJS = require("pptxgenjs");

  ({titleSlide, listSlide, cardSlide, flowSlide, tableSlide, quoteSlide, comparisonSlide, timelineSlide, endSlide, THEME} = require("../api/boxesplus-artist.coffee"));

  pres = new PptxGenJS();

  // 1. 标题页 - 渐变背景
  titleSlide(pres, {
    title: "医院管理课程",
    subtitle: "质量管理与持续改进",
    gradient: "blue"
  });

  // 2. 目录页
  listSlide(pres, {
    title: "课程目录",
    items: ["医疗质量管理概述", "质量管理体系构建", "PDCA循环应用", "质量工具与方法", "案例分析与实践"]
  });

  // 3. 卡片页 - 四宫格
  cardSlide(pres, {
    title: "质量管理四大支柱",
    columns: 2,
    cards: [
      {
        title: "质量控制",
        content: "建立标准，监督执行",
        color: THEME.accent
      },
      {
        title: "质量保证",
        content: "认证评审、风险管理",
        color: THEME.success
      },
      {
        title: "质量改进",
        content: "发现问题，持续提升",
        color: THEME.warning
      },
      {
        title: "质量教育",
        content: "培训学习、文化建设",
        color: THEME.danger
      }
    ]
  });

  // 4. 表格页
  tableSlide(pres, {
    title: "质量指标体系",
    headers: ["指标类别", "核心指标", "目标值"],
    rows: [["结构质量", "人员配置达标率", "≥95%"], ["结构质量", "设备完好率", "≥98%"], ["过程质量", "病历甲级率", "≥90%"], ["过程质量", "核心制度执行率", "100%"], ["结果质量", "患者满意度", "≥90%"]]
  });

  // 5. 引言页
  quoteSlide(pres, {
    quote: "质量不是一种行为，而是一种习惯。",
    author: "亚里士多德"
  });

  // 6. 对比页
  comparisonSlide(pres, {
    title: "传统 vs 现代",
    left: {
      title: "传统模式",
      items: ["经验驱动", "事后检查", "被动应对"]
    },
    right: {
      title: "现代模式",
      items: ["数据驱动", "事前预防", "主动改进"]
    }
  });

  // 7. 时间线
  timelineSlide(pres, {
    title: "工作时间表",
    events: [
      {
        date: "第1周",
        title: "现状调研",
        desc: "了解医院质量现状"
      },
      {
        date: "第2周",
        title: "体系设计",
        desc: "构建质量管理体系"
      },
      {
        date: "第3-4周",
        title: "培训实施",
        desc: "全员质量意识培训"
      }
    ]
  });

  // 8. 结束页
  endSlide(pres, {
    title: "谢谢!",
    subtitle: "让质量成为习惯"
  });

  // 保存
  pres.writeFile({
    fileName: "outputs/demo-artist.pptx"
  }).then(function() {
    return console.log("已创建: outputs/demo-artist.pptx");
  }).catch(function(err) {
    return console.error(err);
  });

}).call(this);
