// Generated by CoffeeScript 2.7.0
(function() {
  // BoxesPlus Artist v2 - 艺术 PPTX 生成器
  var GRADIENTS, PptxGenJS, THEME, cardSlide, comparisonSlide, endSlide, listSlide, quoteSlide, tableSlide, timelineSlide, titleSlide;

  PptxGenJS = require("pptxgenjs");

  THEME = {
    primary: "1a365d",
    secondary: "2c5282",
    accent: "3182ce",
    success: "38a169",
    warning: "d69e2e",
    danger: "e53e3e",
    light: "f7fafc",
    dark: "1a202c",
    text: "2d3748",
    muted: "718096"
  };

  GRADIENTS = {
    blue: ["#2c5282", "#1a365d"],
    green: ["#38a169", "#276749"],
    purple: ["#805ad5", "#553c9a"]
  };

  titleSlide = function(pres, opts) {
    var c1, gradient, slide, subtitle, title;
    ({title, subtitle, gradient} = opts);
    slide = pres.addSlide();
    if (gradient) {
      [c1] = GRADIENTS[gradient] || [THEME.dark];
      slide.background = {
        type: "solid",
        color: c1
      };
    }
    if (title) {
      slide.addText(title, {
        x: 0.5,
        y: 2.5,
        w: 9,
        h: 1.5,
        fontSize: 44,
        color: "ffffff",
        bold: true,
        align: "center"
      });
    }
    if (subtitle) {
      slide.addText(subtitle, {
        x: 1,
        y: 4,
        w: 8,
        h: 0.8,
        fontSize: 20,
        color: "ffffff",
        align: "center",
        transparency: 20
      });
    }
    return slide;
  };

  listSlide = function(pres, opts) {
    var i, item, items, j, len, slide, title, y;
    ({title, items} = opts);
    slide = pres.addSlide();
    
    // 标题
    slide.addText(title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      color: THEME.primary,
      bold: true
    });
    y = 1.2;
    for (i = j = 0, len = items.length; j < len; i = ++j) {
      item = items[i];
      slide.addShape(pres.ShapeType.rect, {
        x: 0.6,
        y: y,
        w: 0.4,
        h: 0.4,
        fill: {
          color: THEME.secondary
        }
      });
      slide.addText(`${i + 1}`, {
        x: 0.6,
        y: y + 0.05,
        w: 0.4,
        h: 0.3,
        fontSize: 12,
        color: "ffffff",
        align: "center"
      });
      slide.addText(item, {
        x: 1.2,
        y: y,
        w: 8,
        h: 0.5,
        fontSize: 16,
        color: THEME.text
      });
      y += 0.6;
    }
    return slide;
  };

  cardSlide = function(pres, opts) {
    var card, cardH, cardW, cards, col, cols, gap, i, j, len, row, slide, startX, startY, title, x, y;
    ({
      title,
      cards,
      columns: cols = 2
    } = opts);
    slide = pres.addSlide();
    slide.addText(title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      color: THEME.primary,
      bold: true
    });
    cardW = 4.2;
    cardH = 2.5;
    gap = 0.3;
    startX = 0.5;
    startY = 1.2;
    for (i = j = 0, len = cards.length; j < len; i = ++j) {
      card = cards[i];
      col = i % cols;
      row = Math.floor(i / cols);
      x = startX + col * (cardW + gap);
      y = startY + row * (cardH + gap);
      slide.addShape(pres.ShapeType.rect, {
        x: x,
        y: y,
        w: cardW,
        h: cardH,
        fill: {
          color: THEME.light
        },
        line: {
          color: THEME.secondary,
          width: 1
        }
      });
      if (card.title) {
        slide.addText(card.title, {
          x: x + 0.2,
          y: y + 0.3,
          w: cardW - 0.4,
          h: 0.5,
          fontSize: 16,
          bold: true,
          color: THEME.primary
        });
      }
      if (card.content) {
        slide.addText(card.content, {
          x: x + 0.2,
          y: y + 0.9,
          w: cardW - 0.4,
          h: cardH - 1.2,
          fontSize: 12,
          color: THEME.text
        });
      }
    }
    return slide;
  };

  tableSlide = function(pres, opts) {
    var bgColor, cell, colW, header, headers, i, j, k, l, len, len1, len2, ri, row, rowH, rows, slide, title, x, y;
    ({title, headers, rows} = opts);
    slide = pres.addSlide();
    slide.addText(title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      color: THEME.primary,
      bold: true
    });
    if (!(headers && headers.length > 0)) {
      return;
    }
    x = 0.5;
    y = 1.2;
    colW = 9 / headers.length;
    rowH = 0.5;
    
    // 表头
    slide.addShape(pres.ShapeType.rect, {
      x: x,
      y: y,
      w: 9,
      h: rowH,
      fill: {
        color: THEME.secondary
      }
    });
    for (i = j = 0, len = headers.length; j < len; i = ++j) {
      header = headers[i];
      slide.addText(header, {
        x: x + i * colW + 0.1,
        y: y + 0.1,
        w: colW - 0.2,
        h: rowH - 0.2,
        fontSize: 14,
        color: "ffffff",
        bold: true
      });
    }
    y += rowH;

    // 数据行
    for (ri = k = 0, len1 = rows.length; k < len1; ri = ++k) {
      row = rows[ri];
      bgColor = ri % 2 === 0 ? THEME.light : "ffffff";
      slide.addShape(pres.ShapeType.rect, {
        x: x,
        y: y,
        w: 9,
        h: rowH,
        fill: {
          color: bgColor
        }
      });
      for (i = l = 0, len2 = row.length; l < len2; i = ++l) {
        cell = row[i];
        slide.addText(cell, {
          x: x + i * colW + 0.1,
          y: y + 0.1,
          w: colW - 0.2,
          h: rowH - 0.2,
          fontSize: 12,
          color: THEME.text
        });
      }
      y += rowH;
    }
    return slide;
  };

  quoteSlide = function(pres, opts) {
    var author, quote, slide;
    ({quote, author} = opts);
    slide = pres.addSlide();
    slide.addShape(pres.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 10,
      h: 5.5,
      fill: {
        color: THEME.primary
      }
    });
    slide.addText('"' + quote + '"', {
      x: 1,
      y: 1.8,
      w: 8,
      h: 2,
      fontSize: 24,
      color: "ffffff",
      italic: true,
      align: "center"
    });
    if (author) {
      slide.addText(`— ${author}`, {
        x: 1,
        y: 4,
        w: 8,
        h: 0.5,
        fontSize: 16,
        color: "ffffff",
        align: "right"
      });
    }
    return slide;
  };

  comparisonSlide = function(pres, opts) {
    var item, j, k, left, len, len1, ref, ref1, right, slide, title, y;
    ({title, left, right} = opts);
    slide = pres.addSlide();
    slide.addText(title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      color: THEME.primary,
      bold: true
    });
    
    // 左侧
    slide.addShape(pres.ShapeType.rect, {
      x: 0.3,
      y: 1.2,
      w: 4.5,
      h: 4,
      fill: {
        color: THEME.light
      },
      line: {
        color: THEME.secondary,
        width: 2
      }
    });
    slide.addText(left.title || "优点", {
      x: 0.5,
      y: 1.4,
      w: 4,
      h: 0.5,
      fontSize: 18,
      color: THEME.success,
      bold: true
    });
    if (left.items) {
      y = 2;
      ref = left.items;
      for (j = 0, len = ref.length; j < len; j++) {
        item = ref[j];
        slide.addText(`✓ ${item}`, {
          x: 0.5,
          y: y,
          w: 4,
          h: 0.4,
          fontSize: 14,
          color: THEME.text
        });
        y += 0.5;
      }
    }
    
    // 右侧
    slide.addShape(pres.ShapeType.rect, {
      x: 5.2,
      y: 1.2,
      w: 4.5,
      h: 4,
      fill: {
        color: THEME.light
      },
      line: {
        color: THEME.danger,
        width: 2
      }
    });
    slide.addText(right.title || "缺点", {
      x: 5.4,
      y: 1.4,
      w: 4,
      h: 0.5,
      fontSize: 18,
      color: THEME.danger,
      bold: true
    });
    if (right.items) {
      y = 2;
      ref1 = right.items;
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        item = ref1[k];
        slide.addText(`✗ ${item}`, {
          x: 5.4,
          y: y,
          w: 4,
          h: 0.4,
          fontSize: 14,
          color: THEME.text
        });
        y += 0.5;
      }
    }
    return slide;
  };

  timelineSlide = function(pres, opts) {
    var event, events, i, j, len, slide, title, y;
    ({title, events} = opts);
    slide = pres.addSlide();
    slide.addText(title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      color: THEME.primary,
      bold: true
    });
    y = 1.5;
    for (i = j = 0, len = events.length; j < len; i = ++j) {
      event = events[i];
      slide.addShape(pres.ShapeType.rect, {
        x: 1,
        y: y,
        w: 0.4,
        h: 0.4,
        fill: {
          color: THEME.accent
        }
      });
      if (i < events.length - 1) {
        slide.addShape(pres.ShapeType.rect, {
          x: 1.2,
          y: y + 0.4,
          w: 0.05,
          h: 0.8,
          fill: {
            color: THEME.accent
          }
        });
      }
      if (event.date) {
        slide.addText(event.date, {
          x: 1.6,
          y: y,
          w: 2,
          h: 0.3,
          fontSize: 12,
          color: THEME.muted
        });
      }
      if (event.title) {
        slide.addText(event.title, {
          x: 1.6,
          y: y + 0.3,
          w: 7,
          h: 0.4,
          fontSize: 16,
          bold: true,
          color: THEME.primary
        });
      }
      if (event.desc) {
        slide.addText(event.desc, {
          x: 1.6,
          y: y + 0.7,
          w: 7,
          h: 0.5,
          fontSize: 12,
          color: THEME.text
        });
      }
      y += 1.3;
    }
    return slide;
  };

  endSlide = function(pres, opts) {
    var slide, subtitle, title;
    ({title, subtitle} = opts);
    slide = pres.addSlide();
    slide.background = {
      type: "solid",
      color: THEME.dark
    };
    if (title) {
      slide.addText(title, {
        x: 0.5,
        y: 2,
        w: 9,
        h: 1,
        fontSize: 40,
        color: "ffffff",
        bold: true,
        align: "center"
      });
    }
    if (subtitle) {
      slide.addText(subtitle, {
        x: 0.5,
        y: 3.2,
        w: 9,
        h: 0.6,
        fontSize: 18,
        color: "ffffff",
        align: "center"
      });
    }
    return slide;
  };

  module.exports = {titleSlide, listSlide, cardSlide, tableSlide, quoteSlide, comparisonSlide, timelineSlide, endSlide, THEME, GRADIENTS};

}).call(this);
