// Generated by CoffeeScript 2.7.0
(function() {
  // BoxesPlus API - 简单 DSL 解析器
  // 用法: coffee boxesplus-api.coffee input.md [output.pptx]
  var Parser, PptxGenJS, Slide, fs, main, path;

  PptxGenJS = require("pptxgenjs");

  fs = require("fs");

  path = require("path");

  // 幻灯片对象
  Slide = class Slide {
    constructor(pres1, type = "content", title1 = "") {
      this.pres = pres1;
      this.type = type;
      this.title = title1;
      this.slide = this.pres.addSlide();
      this.content = [];
      this.options = {};
    }

    setTitle(title) {
      this.title = title;
      return this.slide.addText(title, {
        x: 0.5,
        y: 0.3,
        w: 9,
        h: 0.6,
        fontSize: 28,
        color: "1a365d",
        bold: true
      });
    }

    addList(items) {
      var item, j, len, results, y;
      y = 1.2;
      results = [];
      for (j = 0, len = items.length; j < len; j++) {
        item = items[j];
        this.slide.addText(`• ${item}`, {
          x: 0.8,
          y: y,
          w: 8,
          h: 0.4,
          fontSize: 18,
          color: "2d3748"
        });
        results.push(y += 0.5);
      }
      return results;
    }

    addBox(title, content) {
      var j, len, line, results, y;
      // 标题栏
      this.slide.addShape(this.pres.ShapeType.rect, {
        x: 0.5,
        y: 1,
        w: 9,
        h: 0.7,
        fill: {
          color: "2c5282"
        }
      });
      this.slide.addText(title, {
        x: 0.7,
        y: 1.1,
        w: 8.6,
        h: 0.5,
        fontSize: 18,
        color: "ffffff",
        bold: true
      });
      
      // 内容框
      this.slide.addShape(this.pres.ShapeType.rect, {
        x: 0.5,
        y: 1.9,
        w: 9,
        h: 3.5,
        fill: {
          color: "f7fafc"
        },
        line: {
          color: "2c5282",
          width: 2
        }
      });
      
      // 内容
      y = 2.2;
      results = [];
      for (j = 0, len = content.length; j < len; j++) {
        line = content[j];
        this.slide.addText(line, {
          x: 0.8,
          y: y,
          w: 8.4,
          h: 0.4,
          fontSize: 14,
          color: "2d3748"
        });
        y += 0.45;
        if (y > 5) {
          break;
        } else {
          results.push(void 0);
        }
      }
      return results;
    }

    addFlow(steps) {
      var j, len, results, step, y;
      // 简单的流程图 - 每步一个框
      y = 1.2;
      results = [];
      for (j = 0, len = steps.length; j < len; j++) {
        step = steps[j];
        this.slide.addShape(this.pres.ShapeType.roundRect, {
          x: 1.5,
          y: y,
          w: 6,
          h: 0.6,
          fill: {
            color: "4299e1"
          }
        });
        this.slide.addText(step, {
          x: 1.5,
          y: y + 0.1,
          w: 6,
          h: 0.4,
          fontSize: 14,
          color: "ffffff",
          align: "center"
        });
        results.push(y += 0.8);
      }
      return results;
    }

    addTable(rows) {
      var bg, cell, colW, i, j, l, len, len1, len2, m, ref, ref1, results, ri, row, x, y;
      if (!(rows.length > 0)) {
        return;
      }
      x = 0.5;
      y = 1.2;
      colW = 8 / rows[0].length;
      
      // 表头
      this.slide.addShape(this.pres.ShapeType.rect, {
        x: x,
        y: y,
        w: 8,
        h: 0.5,
        fill: {
          color: "2c5282"
        }
      });
      ref = rows[0];
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        cell = ref[i];
        this.slide.addText(cell, {
          x: x + 0.1,
          y: y + 0.1,
          w: colW - 0.2,
          h: 0.3,
          fontSize: 12,
          color: "ffffff",
          bold: true
        });
        x += colW;
      }
      
      // 数据行
      y += 0.5;
      ref1 = rows.slice(1);
      results = [];
      for (ri = l = 0, len1 = ref1.length; l < len1; ri = ++l) {
        row = ref1[ri];
        x = 0.5;
        bg = ri % 2 === 0 ? "f7fafc" : "ffffff";
        for (m = 0, len2 = row.length; m < len2; m++) {
          cell = row[m];
          this.slide.addText(cell, {
            x: x + 0.1,
            y: y + 0.1,
            w: colW - 0.2,
            h: 0.3,
            fontSize: 11,
            color: "2d3748"
          });
          x += colW;
        }
        results.push(y += 0.4);
      }
      return results;
    }

  };

  // 主解析器
  Parser = class Parser {
    constructor(content1) {
      this.content = content1;
      this.slides = [];
      this.lines = this.content.split('\n');
      this.i = 0;
    }

    parse() {
      var line, pres, slide, title;
      pres = new PptxGenJS();
      while (this.i < this.lines.length) {
        line = this.lines[this.i].trim();
        if (line.startsWith('# ')) {
          // 标题幻灯片
          title = line.slice(2);
          slide = new Slide(pres, "title", title);
          slide.setTitle(title);
          this.slides.push(slide);
          this.i++;
        } else if (line.startsWith('## ')) {
          // 内容幻灯片
          title = line.slice(3);
          slide = new Slide(pres, "content", title);
          slide.setTitle(title);
          this.parseContent(slide);
          this.slides.push(slide);
        } else {
          this.i++;
        }
      }
      return pres;
    }

    parseContent(slide) {
      var boxContent, boxMode, boxTitle, cells, currentRow, flowMode, flowSteps, items, j, k, len, line, s, steps, tableMode, tableRows, v;
      items = [];
      boxMode = false;
      boxTitle = "";
      boxContent = [];
      flowMode = false;
      flowSteps = [];
      tableMode = false;
      tableRows = [];
      currentRow = [];
      while (this.i < this.lines.length) {
        this.i++;
        if (this.i >= this.lines.length) {
          break;
        }
        line = this.lines[this.i].trim();
        
        // 结束标记
        if (line === "}}" || line.startsWith('## ')) {
          this.i--;
          break;
        }
        
        // 列表
        if (line.startsWith('- ')) {
          items.push(line.slice(2));
          continue;
        }
        
        // 方框
        if (line === '{{box}}') {
          boxMode = true;
          continue;
        }
        if (line === '{{/box}}') {
          slide.addBox(boxTitle, boxContent);
          boxMode = false;
          boxTitle = "";
          boxContent = [];
          continue;
        }
        if (boxMode) {
          if (line.includes(':')) {
            [k, v] = line.split(':');
            if (!boxTitle) {
              boxTitle = v.trim();
            } else {
              boxContent.push(`${k}: ${v.trim()}`);
            }
          }
          continue;
        }
        
        // 流程
        if (line === '{{flow}}') {
          flowMode = true;
          continue;
        }
        if (line === '{{/flow}}') {
          slide.addFlow(flowSteps);
          flowMode = false;
          flowSteps = [];
          continue;
        }
        if (flowMode) {
          if (line.includes('->')) {
            steps = line.split('->');
            for (j = 0, len = steps.length; j < len; j++) {
              s = steps[j];
              flowSteps.push(s.trim());
            }
          } else if (line.trim()) {
            flowSteps.push(line.trim());
          }
          continue;
        }
        
        // 表格
        if (line.startsWith('|')) {
          cells = line.split('|').slice(1, -1).map(function(c) {
            return c.trim();
          });
          tableRows.push(cells);
          continue;
        } else if (tableMode && tableRows.length > 0) {
          slide.addTable(tableRows);
          tableRows = [];
          tableMode = false;
        }
        
        // 空行结束
        if (line === '') {
          if (items.length > 0) {
            slide.addList(items);
            items = [];
          }
          if (tableRows.length > 0) {
            slide.addTable(tableRows);
            tableRows = [];
          }
        }
      }
      
      // 最后处理
      if (items.length > 0) {
        slide.addList(items);
      }
      if (tableRows.length > 0) {
        return slide.addTable(tableRows);
      }
    }

  };

  // 主程序
  main = function() {
    var content, inputFile, outputFile, parser, pres;
    inputFile = process.argv[2] || "example.md";
    outputFile = process.argv[3] || inputFile.replace('.md', '.pptx');
    if (!fs.existsSync(inputFile)) {
      console.log("用法: coffee boxesplus-api.coffee input.md [output.pptx]");
      console.log("  input.md  - 输入的markdown文件");
      console.log("  output.pptx - 输出的PPTX文件(可选)");
      process.exit(1);
    }
    content = fs.readFileSync(inputFile, "utf-8");
    parser = new Parser(content);
    pres = parser.parse();
    return pres.writeFile({
      fileName: outputFile
    }).then(function() {
      return console.log(`已创建: ${outputFile}`);
    }).catch(function(err) {
      return console.error(err);
    });
  };

  main();

}).call(this);
