// Generated by CoffeeScript 2.7.0
(function() {
  // BoxesPlus Artist v3 - 完整演示 with Charts
  var THEME, barChartSlide, cardSlide, comparisonSlide, endSlide, lineChartSlide, listSlide, pieChartSlide, pres, quoteSlide, radarChartSlide, tableSlide, timelineSlide, titleSlide;

  ({titleSlide, listSlide, cardSlide, tableSlide, quoteSlide, comparisonSlide, timelineSlide, endSlide, THEME} = require("./boxesplus-artist.coffee"));

  ({barChartSlide, pieChartSlide, lineChartSlide, radarChartSlide} = require("./charts.coffee"));

  pres = new (require("pptxgenjs"))();

  // 标题
  titleSlide(pres, {
    title: "医院运营分析报告",
    subtitle: "2024年度数据展示",
    gradient: "blue"
  });

  // 柱状图 - 科室收入
  barChartSlide(pres, {
    title: "各科室收入对比 (万元)",
    categories: ["内科", "外科", "妇产科", "儿科", "急诊科", "门诊"],
    series: [
      {
        name: "2023年",
        values: [1200,
      1800,
      900,
      600,
      800,
      1500]
      },
      {
        name: "2024年",
        values: [1400,
      2100,
      1000,
      750,
      950,
      1800]
      }
    ]
  });

  // 饼图 - 收入构成
  pieChartSlide(pres, {
    title: "医院收入构成",
    labels: ["药品收入", "检查收入", "手术收入", "住院收入", "其他收入"],
    values: [35, 20, 25, 15, 5]
  });

  // 折线图 - 门诊量趋势
  lineChartSlide(pres, {
    title: "月度门诊量趋势 (万人次)",
    categories: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    series: [
      {
        name: "2023年",
        values: [12,
      10,
      15,
      18,
      20,
      22,
      25,
      24,
      21,
      19,
      16,
      14]
      },
      {
        name: "2024年",
        values: [14,
      12,
      18,
      22,
      25,
      28,
      30,
      29,
      25,
      22,
      18,
      16]
      }
    ]
  });

  // 雷达图 - 科室综合评价
  radarChartSlide(pres, {
    title: "科室综合评价",
    categories: ["医疗质量", "服务态度", "运营效率", "科研教学", "成本控制", "患者满意度"],
    series: [
      {
        name: "内科",
        values: [85,
      80,
      75,
      70,
      80,
      85]
      },
      {
        name: "外科",
        values: [90,
      75,
      85,
      65,
      70,
      80]
      }
    ]
  });

  // 列表
  listSlide(pres, {
    title: "报告要点",
    items: ["收入稳步增长", "科室发展不均衡", "门诊量创新高", "成本控制有成效"]
  });

  // 结束
  endSlide(pres, {
    title: "谢谢!",
    subtitle: "数据驱动决策"
  });

  // 保存
  pres.writeFile({
    fileName: "outputs/demo-charts.pptx"
  }).then(function() {
    return console.log("已创建: outputs/demo-charts.pptx");
  }).catch(function(err) {
    return console.error(err);
  });

}).call(this);
